[pytest]

# Pytest command line options
addopts =
    -v
    -s
    --html=reports/report.html
    --self-contained-html

# Pytest will only search inside:
# tests/
#This makes execution cleaner and faster.
testpaths = tests

# Detect all test files starting with test_
python_files = test_*.py